---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openstack-exporter
  namespace: monitoring
  labels:
    infra: openstack-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        infra: openstack-exporter
    spec:
      containers:
      - name: openstack-exporter
        image: quay.io/niedbalski/openstack-exporter:v0.0.7
        args:
        - default
        - --disable-service.volume
        ports:
        - containerPort: 9180
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/openstack/clouds.yml
            subPath: clouds.yaml
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
         readOnlyRootFilesystem: true
         runAsNonRoot: true
         runAsUser: 20000
         capabilities:
           drop:
             - ALL
           add:
             - NET_BIND_SERVICE
      volumes:
      - name: config
        configMap:
          name: openstack-exporter-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    infra: openstack-exporter
  name: openstack-exporter-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9180
    targetPort: 9180
    name: http
  selector:
    infra: openstack-exporter
